/**
 * @file types.ts
 * @description Core TypeScript type definitions for AlbionOS.
 *
 * Every interface in this file maps 1-to-1 to a table (or view) in the
 * Supabase PostgreSQL database. Field names use `snake_case` to match the
 * database column names exactly, which lets Supabase's auto-generated
 * types and RPC calls work without manual mapping.
 *
 * **Architecture role:**
 * - Shared across client components, server components, API routes,
 *   and utility functions so there is a single source of truth for
 *   every domain entity.
 * - Union types (e.g. `InvoiceStatus`) mirror PostgreSQL `CHECK`
 *   constraints and enums, keeping front-end validation in sync with
 *   the database.
 *
 * **Key exports:**
 * - Domain models: `User`, `Location`, `Product`, `InventoryItem`,
 *   `Customer`, `Invoice`, `InvoiceItem`, `Payment`, `ChatMessage`
 * - Aggregate DTO: `DashboardStats`
 * - Union / enum types: `UserRole`, `LocationType`, `InventoryStatus`,
 *   `InvoiceStatus`, `PaymentMethod`, `PaymentStatus`
 */

/* ============================================================
   Roles
   ============================================================ */

/**
 * The five application-level roles.
 *
 * Stored in the `users.role` column as a text value.
 *
 * | Value               | Description                                       |
 * |---------------------|---------------------------------------------------|
 * | `super_admin`       | Full platform access, can manage users & settings |
 * | `sales_rep`         | Field rep — creates orders, manages customers     |
 * | `finance_manager`   | Approves payments, generates financial reports    |
 * | `inventory_manager` | Manages product catalog and warehouse stock       |
 * | `ceo`               | Chief Executive Officer — read-only executive     |
 */
export type UserRole =
  | 'super_admin'
  | 'sales_rep'
  | 'finance_manager'
  | 'inventory_manager'
  | 'ceo'
  | 'clinic_admin'
  | 'vet'
  | 'vet_tech'
  | 'vet_assistant'
  | 'receptionist'
  | 'regional_manager'
  | 'security'
  | 'lab_scientist'
  | 'pharmacist'
  | 'support_staff';


/* ============================================================
   User  →  Supabase table: `users`
   ============================================================ */

/**
 * A registered user of the AlbionOS platform.
 *
 * Maps to the `users` table in Supabase. The `id` is a UUID generated by
 * Supabase Auth; the remaining profile fields are stored in a public
 * `users` table joined on `id`.
 */
export interface User {
  /** UUID primary key — matches the Supabase Auth `auth.users.id`. */
  id: string;

  /** Corporate email, unique, used as the login credential. */
  email: string;

  /** Full display name (e.g. "Dr. Emeka Moneke"). */
  full_name: string;

  /** The user's assigned primary role. Determines navigation and data access. */
  role: UserRole;

  /** Optional array of additional or concurrent roles for multi-role personnel. */
  roles?: UserRole[];

  /** FK → `locations.id`. Nullable for super admins who see all locations. */
  location_id: string | null;

  /** URL of the user's profile picture stored in Supabase Storage. */
  avatar_url: string | null;

  /** Phone number in E.164-ish format (e.g. "+234 803 000 0001"). */
  phone: string | null;

  /** ISO 8601 timestamp of when the user account was created. */
  created_at: string;

  /** Indicates if the user account is active or soft-deleted/suspended. */
  is_active: boolean;
}

/* ============================================================
   Location  →  Supabase table: `locations`
   ============================================================ */

/**
 * Classification of a physical Albion Pharmaceuticals location.
 *
 * | Value       | Meaning                                         |
 * |-------------|-------------------------------------------------|
 * | `warehouse` | Storage/distribution centre (e.g. HQ Warehouse) |
 * | `territory` | Sales territory covering a geographic region     |
 * | `clinic`    | A clinic or pharmacy that purchases products     |
 */
export type LocationType = 'warehouse' | 'territory' | 'clinic';

/**
 * A physical or logical location within the Albion distribution network.
 *
 * Maps to the `locations` table. Every product batch, user, and customer
 * is associated with exactly one location.
 */
export interface Location {
  /** UUID primary key. */
  id: string;

  /** Human-readable name (e.g. "HQ Warehouse", "Lagos Territory"). */
  name: string;

  /** Categorisation of the location. */
  type: LocationType;

  /** Geographic region (e.g. "South-East", "South-West"). */
  region: string;

  /** Nigerian state the location resides in (e.g. "Anambra", "Lagos"). */
  state: string;

  /** Full street address for warehouses/clinics; general area for territories. */
  address: string;
}

/* ============================================================
   Product  →  Supabase table: `products`
   ============================================================ */

/**
 * A pharmaceutical product in the Albion catalog.
 *
 * Maps to the `products` table. Each product has a unique SKU and a
 * NAFDAC (National Agency for Food and Drug Administration and Control)
 * registration number required by Nigerian regulation.
 */
export interface Product {
  /** UUID primary key. */
  id: string;

  /** Commercial product name (e.g. "Albion Paracetamol 500mg"). */
  name: string;

  /** Stock Keeping Unit — unique alphanumeric code for internal tracking. */
  sku: string;

  /** NAFDAC registration number — required for legal sale in Nigeria. */
  nafdac_number: string;

  /** Price per sellable unit in Nigerian Naira (₦). */
  unit_price: number;

  /** Product category (e.g. "Analgesic", "Antibiotic", "Vitamin"). */
  category: string;

  /** Optional longer description shown on the product detail page. */
  description: string | null;

  /** URL of the product photo stored in Supabase Storage. */
  image_url: string | null;

  /** ISO 8601 timestamp of when the product was added to the catalog. */
  created_at: string;

  /** Indicates if the product is active or soft-deleted/discontinued. */
  is_active: boolean;
}

/* ============================================================
   Inventory  →  Supabase table: `inventory`
   ============================================================ */

/**
 * Stock status of an inventory batch.
 *
 * Computed from `quantity` and `expiry_date` fields:
 *
 * | Value          | Condition                                     |
 * |----------------|-----------------------------------------------|
 * | `in_stock`     | quantity > low-stock threshold & not expired   |
 * | `low_stock`    | quantity ≤ threshold & not zero                |
 * | `out_of_stock` | quantity === 0                                 |
 * | `expired`      | expiry_date is in the past                    |
 */
export type InventoryStatus =
  | 'in_stock'
  | 'low_stock'
  | 'out_of_stock'
  | 'expired';

/**
 * A single batch of a product held at a specific location.
 *
 * Maps to the `inventory` table. The compound key of
 * `(product_id, location_id, batch_number)` is unique.
 */
export interface InventoryItem {
  /** UUID primary key. */
  id: string;

  /** FK → `products.id`. The product this batch contains. */
  product_id: string;

  /** FK → `locations.id`. The warehouse/territory holding this batch. */
  location_id: string;

  /** Number of sellable units currently in stock. */
  quantity: number;

  /** Manufacturer's batch/lot number for traceability. */
  batch_number: string;

  /** ISO 8601 date after which this batch must not be sold. */
  expiry_date: string;

  /** Current stock status. May be updated by a scheduled job or trigger. */
  status: InventoryStatus;
}

/* ============================================================
   Customer  →  Supabase table: `customers`
   ============================================================ */

/**
 * A pharmacy, hospital, or distributor that purchases from Albion.
 *
 * Maps to the `customers` table. Each customer is assigned to one
 * location (territory) and managed by the sales rep in that territory.
 */
export interface Customer {
  /** UUID primary key. */
  id: string;

  /** Contact person's full name. */
  name: string;

  /** Registered business/pharmacy name. */
  business_name: string;

  /** Primary phone number. */
  phone: string;

  /** Optional email address. */
  email: string | null;

  /** Physical address of the business. */
  address: string;

  /** Nigerian state the customer operates in. */
  state: string;

  /** Maximum credit (₦) the customer is allowed before payment is required. */
  credit_limit: number;

  /** Total unpaid amount (₦) across all invoices. Updated by payment events. */
  outstanding_balance: number;

  /** FK → `locations.id`. The territory this customer belongs to. */
  location_id: string;

  /** Indicates if the customer is active or soft-deleted. */
  is_active: boolean;
}

/* ============================================================
   Invoice  →  Supabase tables: `invoices` + `invoice_items`
   ============================================================ */

/**
 * Lifecycle status of an invoice.
 *
 * | Value     | Meaning                                            |
 * |-----------|----------------------------------------------------|
 * | `draft`   | Created but not yet sent to the customer            |
 * | `sent`    | Delivered to the customer, awaiting payment         |
 * | `paid`    | Fully paid — outstanding amount is zero             |
 * | `partial` | Partially paid — some balance remains               |
 * | `overdue` | Past the `due_date` with an outstanding balance     |
 */
export type InvoiceStatus =
  | 'draft'
  | 'sent'
  | 'paid'
  | 'partial'
  | 'overdue'
  | 'cancelled';

/**
 * A single line item within an invoice.
 *
 * Maps to the `invoice_items` table. An invoice has one or more items.
 */
export interface InvoiceItem {
  /** UUID primary key. */
  id: string;

  /** FK → `products.id`. */
  product_id: string;

  /** Denormalised product name for display (avoids extra join on read). */
  product_name: string;

  /** Number of units sold in this line item. */
  quantity: number;

  /** Price per unit (₦) at the time of invoicing (may differ from catalog price). */
  unit_price: number;

  /** Line total (₦): `quantity × unit_price`. */
  total: number;
}

/**
 * A sales invoice issued to a customer.
 *
 * Maps to the `invoices` table. Contains header-level data; line items
 * are stored separately in `InvoiceItem[]`.
 */
export interface Invoice {
  /** UUID primary key. */
  id: string;

  /** Human-readable invoice number (e.g. "INV-2026-001"). Auto-generated. */
  invoice_number: string;

  /** FK → `customers.id`. The customer being billed. */
  customer_id: string;

  /** FK → `users.id`. The sales rep who created the invoice. */
  sales_rep_id: string;

  /** FK → `locations.id`. The territory/warehouse the order ships from. */
  location_id: string;

  /** Array of line items (embedded from `invoice_items` table). */
  items: InvoiceItem[];

  /** Sum of all line item totals before tax (₦). */
  subtotal: number;

  /** VAT amount (₦). Currently 7.5% in Nigeria. */
  vat: number;

  /** Grand total (₦): `subtotal + vat - (discount_amount || 0)`. */
  total: number;

  /** Custom VAT percentage (e.g. 7.5, or 0 for exempt). */
  vat_rate?: number;

  /** Discount type applied ('percent' | 'fixed'). */
  discount_type?: 'percent' | 'fixed';

  /** Discount value (e.g. 5 for 5% or 5000 for ₦5,000). */
  discount_value?: number;

  /** Total discount deducted in ₦. */
  discount_amount?: number;

  /** Current lifecycle status. */
  status: InvoiceStatus;

  /** Total amount paid so far (₦). */
  paid_amount?: number;

  /** ISO 8601 timestamp of invoice creation. */
  created_at: string;

  /** ISO 8601 date by which payment is expected. */
  due_date: string;
}

/* ============================================================
   Payment  →  Supabase table: `payments`
   ============================================================ */

/**
 * How the customer paid.
 *
 * | Value           | Description                              |
 * |-----------------|------------------------------------------|
 * | `cash`          | Physical cash payment to the sales rep   |
 * | `bank_transfer` | Electronic bank transfer (with proof)    |
 */
export type PaymentMethod = 'cash' | 'bank_transfer';

/**
 * Approval status of a payment record.
 *
 * | Value      | Description                                          |
 * |------------|------------------------------------------------------|
 * | `pending`  | Recorded by the sales rep, awaiting finance approval  |
 * | `approved` | Verified and approved by a finance manager             |
 * | `rejected` | Rejected — proof insufficient or amount mismatch      |
 */
export type PaymentStatus = 'pending' | 'approved' | 'rejected';

/**
 * A payment received against an invoice.
 *
 * Maps to the `payments` table. A single invoice can have multiple
 * partial payments until the outstanding balance reaches zero.
 */
export interface Payment {
  /** UUID primary key. */
  id: string;

  /** FK → `invoices.id`. The invoice this payment applies to. */
  invoice_id: string;

  /** FK → `customers.id`. The customer who made the payment. */
  customer_id: string;

  /** Amount paid (₦). May be less than the invoice total (partial payment). */
  amount: number;

  /** How the payment was made. */
  method: PaymentMethod;

  /** URL of uploaded payment proof (e.g. bank transfer receipt image). */
  proof_url: string | null;

  /** Current approval status. */
  status: PaymentStatus;

  /** FK → `users.id`. The sales rep who recorded this payment. */
  recorded_by: string;

  /** FK → `users.id`. The finance manager who approved/rejected. Null until actioned. */
  approved_by: string | null;

  /** Optional free-text notes (e.g. rejection reason). */
  notes: string | null;

  /** ISO 8601 timestamp of when the payment was recorded. */
  created_at: string;
}

/* ============================================================
   Chat  →  Supabase table: `chat_messages`
   ============================================================ */

/**
 * A single message in the internal chat system.
 *
 * Maps to the `chat_messages` table. Messages are direct (1-to-1)
 * between a sender and a receiver. Group chat is not yet supported.
 */
export interface ChatMessage {
  /** UUID primary key. */
  id: string;

  /** FK → `users.id`. The user who sent the message. */
  sender_id: string;

  /** FK → `users.id`. The intended recipient. */
  receiver_id: string;

  /** The text body of the message. */
  content: string;

  /** URL of an attached file (image, PDF, etc.) in Supabase Storage. */
  attachment_url: string | null;

  /** MIME-type hint for the attachment (e.g. "image/png", "application/pdf"). */
  attachment_type: string | null;

  /** Whether the receiver has opened/read this message. */
  is_read: boolean;

  /** ISO 8601 timestamp of when the message was sent. */
  created_at: string;
}

/* ============================================================
   Dashboard  →  Aggregated view / RPC result
   ============================================================ */

/**
 * Aggregated statistics displayed on the main Dashboard page.
 *
 * Unlike the other interfaces this does **not** map to a single table.
 * The values are computed by a Supabase RPC function (or client-side
 * aggregation during the mock phase) that joins across invoices,
 * payments, inventory, and users.
 */
export interface DashboardStats {
  /** Total revenue (₦) from all paid/partial invoices. */
  total_revenue: number;

  /** Total outstanding receivables (₦) across all unpaid invoices. */
  total_receivables: number;

  /** Number of sales reps currently active on the platform. */
  active_reps: number;

  /** Total value (₦) of all products currently in stock. */
  inventory_value: number;

  /** Count of payments in `pending` status awaiting finance approval. */
  pending_payments: number;

  /** Count of inventory batches expiring within the next 90 days. */
  expiring_soon: number;
}

/* ============================================================
   Staff & Salary Management
   ============================================================ */

export type LeaveType = 'annual' | 'sick' | 'personal' | 'maternity' | 'paternity' | 'study';

export type LeaveStatus = 'pending' | 'approved' | 'rejected' | 'cancelled';

export type PayrollRunStatus = 'draft' | 'processing' | 'completed' | 'cancelled';

export type AttendanceStatus = 'present' | 'absent' | 'late' | 'half_day' | 'on_leave';

export type TargetType = 'monthly' | 'quarterly' | 'annual';

export type TargetStatus = 'active' | 'achieved' | 'missed' | 'cancelled';

export type DocumentType = 'contract' | 'id_card' | 'certification' | 'degree' | 'nafdac_license' | 'other';

export interface CustomPayrollAdjustment {
  id: string;
  label: string;
  type: 'flat' | 'percentage';
  value: number;
  amount: number;
}

export interface SalaryGrade {
  id: string;
  grade: string;
  min_salary: number;
  max_salary: number;
  housing_allowance_pct: number;
  transport_allowance_pct: number;
  medical_allowance_pct: number;
  created_at: string;
}

export interface Salary {
  id: string;
  user_id: string;
  salary_grade_id: string;
  basic_salary: number;
  housing_allowance: number;
  transport_allowance: number;
  medical_allowance: number;
  total_gross: number;
  tax_rate: number;
  pension_rate: number;
  nhis_rate: number;
  tax_deduction?: number;
  loan_repayment?: number;
  unmet_target_penalty?: number;
  custom_deductions?: CustomPayrollAdjustment[];
  custom_additions?: CustomPayrollAdjustment[];
  total_deductions: number;
  net_pay: number;
  effective_date: string;
  is_active: boolean;
  created_at: string;
  updated_at: string;
}

export interface PayrollRun {
  id: string;
  period_start: string;
  period_end: string;
  payment_date: string;
  status: PayrollRunStatus;
  total_gross: number;
  total_deductions: number;
  total_net: number;
  employee_count: number;
  processed_by: string;
  created_at: string;
  updated_at: string;
}

export interface Payslip {
  id: string;
  payroll_run_id: string;
  user_id: string;
  basic_salary: number;
  housing_allowance: number;
  transport_allowance: number;
  medical_allowance: number;
  gross_pay: number;
  paye_tax: number;
  pension_deduction: number;
  nhis_deduction: number;
  tax_deduction?: number;
  loan_repayment?: number;
  unmet_target_penalty?: number;
  custom_deductions?: CustomPayrollAdjustment[];
  custom_additions?: CustomPayrollAdjustment[];
  total_deductions: number;
  net_pay: number;
  created_at: string;
}

export interface BranchExpense {
  id: string;
  location_id: string;
  location_name?: string;
  category: 'inventory_purchase' | 'utilities' | 'payroll' | 'maintenance' | 'rent' | 'equipment' | 'fuel' | 'consumables' | 'other';
  amount: number;
  description: string;
  expense_date: string;
  recorded_by: string;
  recorder_name?: string;
  vendor_name?: string | null;
  vendor?: string | null;
  payment_method?: 'cash' | 'bank_transfer' | 'pos' | 'check';
  receipt_url?: string | null;
  created_at: string;
}

export interface BranchFinancialInsights {
  location_id: string;
  location_name: string;
  location_type: string;
  total_inflow: number;
  total_expenditure: number;
  expenses_breakdown: { category: string; amount: number }[];
  net_margin: number;
  profitability_rate: number;
}

export interface LeaveRequest {
  id: string;
  user_id: string;
  leave_type: LeaveType;
  start_date: string;
  end_date: string;
  duration_days: number;
  reason: string;
  status: LeaveStatus;
  approved_by: string | null;
  reviewed_at: string | null;
  reviewer_notes: string | null;
  created_at: string;
  updated_at: string;
}

export interface LeaveBalance {
  id: string;
  user_id: string;
  leave_type: LeaveType;
  total_days: number;
  used_days: number;
  remaining_days: number;
  year: number;
  created_at: string;
  updated_at: string;
}

export interface AttendanceLog {
  id: string;
  user_id: string;
  date: string;
  clock_in: string | null;
  clock_out: string | null;
  status: AttendanceStatus;
  hours_worked: number | null;
  notes: string | null;
  created_at: string;
  updated_at: string;
}

export interface EmployeeDocument {
  id: string;
  user_id: string;
  document_type: DocumentType;
  document_name: string;
  file_url: string;
  file_size: number | null;
  expiry_date: string | null;
  is_verified: boolean;
  verified_by: string | null;
  notes: string | null;
  created_at: string;
  updated_at: string;
}

export interface PerformanceTarget {
  id: string;
  user_id: string;
  target_type: TargetType;
  period_start: string;
  period_end: string;
  sales_target: number;
  actual_sales: number;
  collection_target: number;
  actual_collection: number;
  new_customers_target: number;
  new_customers_actual: number;
  status: TargetStatus;
  notes: string | null;
  created_at: string;
  updated_at: string;
}

export interface PerformanceReview {
  id: string;
  user_id: string;
  reviewer_id: string;
  review_period: string;
  sales_achievement: number | null;
  collection_rate: number | null;
  customer_satisfaction: number | null;
  overall_rating: number | null;
  comments: string | null;
  created_at: string;
  updated_at: string;
}

/* ============================================================
   Pet Clinic Management
   ============================================================ */

export type Species = 'Dog' | 'Cat' | 'Bird' | 'Rabbit' | 'Fish' | 'Reptile' | 'Horse' | 'Goat' | 'Sheep' | 'Cattle' | 'Poultry' | 'Other';

export type PetGender = 'Male' | 'Female';

export type AppointmentStatus = 'scheduled' | 'confirmed' | 'checked_in' | 'in_progress' | 'completed' | 'cancelled' | 'no_show';

export type TreatmentStatus = 'ongoing' | 'completed' | 'cancelled' | 'referred';

export type QueueStatus = 'waiting' | 'in_progress' | 'in_consultation' | 'completed' | 'cancelled' | 'no_show';

export type QueuePriority = 'normal' | 'urgent' | 'emergency';

export type PreferredContactMethod = 'Phone' | 'WhatsApp' | 'Email' | 'SMS';

export interface ClinicClient {
  id: string;
  first_name: string;
  last_name: string;
  full_name: string;
  phone: string;
  alternate_phone?: string | null;
  email?: string | null;
  address: string;
  city?: string | null;
  state?: string | null;
  emergency_contact_name?: string | null;
  emergency_contact_phone?: string | null;
  emergency_contact_relation?: string | null;
  preferred_contact?: PreferredContactMethod;
  referral_source?: string | null;
  notes?: string | null;
  location_id?: string | null;
  is_active: boolean;
  created_at: string;
  updated_at: string;
  patients?: PatientRef[];
  patient_count?: number;
}

export interface AddClinicClientInput {
  first_name: string;
  last_name: string;
  email?: string | null;
  phone: string;
  alternate_phone?: string | null;
  address: string;
  city?: string | null;
  state?: string | null;
  emergency_contact_name?: string | null;
  emergency_contact_phone?: string | null;
  emergency_contact_relation?: string | null;
  preferred_contact?: PreferredContactMethod;
  referral_source?: string | null;
  notes?: string | null;
  location_id?: string | null;
}

export interface Patient {
  id: string;
  owner_id: string;
  location_id: string | null;
  name: string;
  species: Species;
  breed: string | null;
  gender: PetGender;
  date_of_birth: string | null;
  age_years: number | null;
  age_months: number | null;
  weight_kg: number | null;
  color: string | null;
  microchip_id: string | null;
  spayed_neutered: boolean;
  allergies: string | null;
  medical_notes: string | null;
  is_active: boolean;
  created_at: string;
  updated_at: string;
}

export interface Appointment {
  id: string;
  patient_id: string;
  owner_id: string;
  vet_id: string | null;
  location_id: string | null;
  procedure_type: string | null;
  /** Alias for procedure_type */
  service_type?: string | null;
  date: string;
  time: string;
  /** Alias for time */
  start_time?: string;
  duration_minutes: number;
  reason: string | null;
  status: AppointmentStatus;
  notes: string | null;
  created_at: string;
  updated_at: string;
}

export interface Treatment {
  id: string;
  patient_id: string;
  vet_id: string | null;
  location_id: string | null;
  date: string;
  chief_complaint: string | null;
  diagnosis: string | null;
  assessment: string | null;
  plan: string | null;
  status: TreatmentStatus;
  follow_up_date: string | null;
  total_cost: number;
  created_at: string;
  updated_at: string;
}

export interface TreatmentMedication {
  id: string;
  treatment_id: string;
  inventory_item_id: string | null;
  drug_name: string;
  dosage: string;
  route: string;
  frequency: string;
  duration: string;
  quantity: number;
  unit_price: number;
  total: number;
  created_at: string;
}

export interface PatientQueue {
  id: string;
  patient_id: string;
  owner_id: string;
  location_id: string | null;
  department: string;
  priority: QueuePriority;
  status: QueueStatus;
  reason: string | null;
  /** Alias for reason */
  reason_for_visit?: string | null;
  /** Alias for priority */
  triage_level?: QueuePriority;
  assigned_vet_id: string | null;
  called_at: string | null;
  completed_at: string | null;
  created_at: string;
  updated_at: string;
}

export interface ProcedureMedicationProtocol {
  drug_name: string;
  dosage: string;
  frequency: string;
  duration: string;
  is_alternative?: boolean;
}

export interface VetService {
  id: string;
  name: string;
  description: string | null;
  category: string;
  species: string;
  price: number;
  duration_minutes?: number;
  medication_protocol?: ProcedureMedicationProtocol[];
  post_op_notes?: string;
  is_active: boolean;
  created_at: string;
  updated_at: string;
}

export interface Supplier {
  id: string;
  name: string;
  contact_person: string | null;
  phone: string | null;
  email: string | null;
  address: string | null;
  is_active: boolean;
  created_at: string;
  updated_at: string;
}

/* ============================================================
   Joined / relational row types (Supabase `select` with joins)
   ============================================================ */

/** Shape of the `owner:owner_id(...)` join used by clinic queries. */
export interface ClinicOwner {
  id: string;
  full_name: string | null;
  name?: string | null;
  phone?: string | null;
  email?: string | null;
  address?: string | null;
}

/** Minimal `patients` projection returned by the `patient:patient_id(...)` join. */
export interface PatientRef {
  id: string;
  name: string;
  species: string;
  weight_kg?: number | null;
}

/** `patients` row + optional `owner` join. */
export interface PatientWithOwner extends Patient {
  owner?: ClinicOwner | null;
}

/** `appointments` row + optional `patient` / `owner` joins. */
export interface AppointmentWithRelations extends Appointment {
  patient?: PatientRef | null;
  owner?: ClinicOwner | null;
}

/** `patient_queue` row + optional `patient` / `owner` joins. */
export interface PatientQueueWithRelations extends PatientQueue {
  patient?: PatientRef | null;
  owner?: ClinicOwner | null;
}

/** `treatments` row + optional `patient` / `vet` joins. */
export interface TreatmentWithRelations extends Treatment {
  patient?: PatientRef | null;
  vet?: ClinicOwner | null;
}

/** Authenticated user profile representation */
export interface AuthUser {
  id: string;
  email: string;
  full_name: string;
  role: UserRole;
  roles?: UserRole[];
  location_id: string;
  location_name: string;
  avatar_url?: string | null;
  phone: string;
}



export type StockMovementType =
  | 'allocation'
  | 'return'
  | 'receipt'
  | 'adjustment'
  | 'write_off'
  | 'sale';

export interface StockMovement {
  id: string;
  product_id: string;
  from_location_id: string | null;
  to_location_id: string | null;
  supplier_id: string | null;
  quantity: number;
  movement_type: StockMovementType;
  reference_id: string | null;
  notes: string | null;
  performed_by: string | null;
  created_at: string;
}

/** `stock_movements` row + optional `product` / location joins. */
export interface StockMovementWithRelations extends StockMovement {
  product?: { name: string } | null;
  from_location?: { name: string } | null;
  to_location?: { name: string } | null;
}

/* ============================================================
   Clinical Specialty Modules Types
   ============================================================ */

/* ── Diagnostic Lab Hub ── */
export type LabTestType =
  | 'cbc'
  | 'biochemistry'
  | 'urinalysis'
  | 'parasitology'
  | 'pathology'
  | 'complete_blood_count'
  | 'fecal_analysis'
  | 'cytology'
  | 'rapid_snap_test'
  | 'other';

export type LabStatus =
  | 'pending'
  | 'sample_collected'
  | 'collected'
  | 'processing'
  | 'ready'
  | 'reviewed'
  | 'rejected';

export interface LabResultParameter {
  name?: string;
  parameter?: string;
  value: number | string;
  unit: string;
  reference_range: string;
  flag?: 'normal' | 'low' | 'high' | 'critical';
  status?: 'normal' | 'low' | 'high' | 'critical';
}

export interface LabOrder {
  id: string;
  order_number: string;
  patient_id: string;
  patient_name?: string;
  species?: string;
  breed?: string;
  owner_name?: string;
  doctor_id?: string;
  doctor_name?: string;
  test_type: LabTestType;
  status: LabStatus;
  priority?: 'normal' | 'urgent';
  notes?: string;
  clinical_notes?: string;
  location_id?: string;
  results?: LabResultParameter[];
  pathology_summary?: string;
  collected_at: string;
  completed_at?: string | null;
  reviewed_by?: string | null;
}

/* ── Inpatient ICU & Hospitalization ── */
export type WardType = 'general_ward' | 'icu' | 'isolation' | 'recovery' | 'post_op' | 'quarantine';
export type HospitalizationStatus = 'active' | 'stable' | 'critical' | 'discharged' | 'admitted' | 'ready_for_discharge';

export interface ICUVitalEntry {
  id: string;
  timestamp: string;
  temperature_c: number;
  heart_rate_bpm: number;
  respiratory_rate_bpm: number;
  crt_seconds?: number;
  capillary_refill_sec?: number;
  mucous_membranes: 'pink' | 'pale' | 'cyanotic' | 'icteric' | 'hyperemic' | string;
  blood_pressure_sys?: number;
  blood_pressure_dia?: number;
  fluid_rate_ml_hr?: number;
  pain_score?: number;
  mental_status?: string;
  notes?: string;
  logged_by: string;
}

export interface HospitalizationRecord {
  id: string;
  patient_id: string;
  patient_name?: string;
  species?: string;
  cage_number: string;
  ward?: WardType;
  ward_type?: WardType;
  admission_date: string;
  reason_for_admission?: string;
  admitting_diagnosis?: string;
  attending_vet_id?: string;
  attending_vet_name?: string;
  status: HospitalizationStatus;
  weight_kg?: number;
  fluid_rate_ml_hr?: number;
  special_instructions?: string;
  location_id?: string;
  vitals: ICUVitalEntry[];
  discharge_date?: string | null;
  discharge_summary?: string | null;
}

/* ── Surgical Suite & Anesthesia ── */
export type SurgeryStatus = 'scheduled' | 'pre_op' | 'in_surgery' | 'recovery' | 'completed' | 'cancelled';

export interface SurgeryRecord {
  id: string;
  surgery_number: string;
  patient_id: string;
  patient_name?: string;
  procedure_name: string;
  primary_surgeon?: string;
  surgeon_name?: string;
  theater_room?: string;
  anesthetist?: string;
  anesthesia_protocol?: string;
  status: SurgeryStatus;
  scheduled_date: string;
  pre_op_checklist?: {
    fasting_confirmed?: boolean;
    consent_signed?: boolean;
    iv_catheter_placed?: boolean;
    pre_medication_given?: boolean;
  };
  anesthesia_agent?: string;
  duration_minutes?: number;
  blood_loss_ml?: number;
  surgical_notes?: string;
  post_op_instructions?: string;
  location_id?: string;
}

/* ── Cash Reconciliation ── */
export type ReconciliationStatus = 'balanced' | 'discrepancy' | 'approved';

export interface CashReconciliation {
  id: string;
  date?: string;
  shift_date?: string;
  shift_type?: 'morning' | 'evening' | 'full_day';
  reconciled_by?: string;
  cashier_id?: string;
  location_id?: string;
  cash_expected: number;
  cash_actual: number;
  pos_card_expected: number;
  pos_card_actual: number;
  bank_transfer_expected: number;
  bank_transfer_actual: number;
  total_expected: number;
  total_actual: number;
  variance: number;
  status: ReconciliationStatus;
  discrepancy_reason?: string;
  approved_by?: string | null;
  created_at: string;
}

/* ── Clinical Calculators ── */
export interface DrugDoseResult {
  weightKg: number;
  doseMgKg: number;
  totalDoseMg: number;
  concentrationMgMl: number;
  volumeMl: number;
}

export interface FluidRateResult {
  weightKg: number;
  maintenanceMlDay: number;
  dehydrationDeficitMl: number;
  ongoingLossesMlDay: number;
  total24hMl: number;
  hourlyRateMlHr: number;
  dropsPerMinute: number;
}

/* ── Audit Log Vault ── */
export type AuditCategory =
  | 'financial'
  | 'narcotics'
  | 'inventory'
  | 'security'
  | 'clinical'
  | 'system';

export type AuditSeverity = 'info' | 'warning' | 'critical';

export interface AuditLog {
  id: string;
  table_name: string;
  record_id: string;
  action: string;
  actor_id: string;
  actor_name?: string;
  actor_role: string;
  user_id?: string;
  user_name?: string;
  entity_type?: string;
  entity_id?: string;
  category: AuditCategory;
  severity: AuditSeverity;
  details: Record<string, any> | null;
  ip_address?: string | null;
  created_at: string;
}

/* ── Shift Timetable & Duty Roster ── */
export type ShiftBlock = 'morning' | 'afternoon' | 'night' | 'on_call';

export interface ClinicShift {
  id: string;
  user_id: string;
  staff_name?: string;
  role?: string;
  location_id: string;
  location_name?: string;
  shift_date: string;
  shift_block: ShiftBlock;
  start_time: string;
  end_time: string;
  notes?: string | null;
  created_at: string;
}

/* ── Preventive Care & Reminders ── */
export type ReminderType = 'vaccination' | 'deworming' | 'suture_removal' | 'medication_refill' | 'wellness_check';
export type ReminderStatus = 'pending' | 'sent' | 'completed' | 'cancelled';

export interface PatientReminder {
  id: string;
  patient_id: string;
  patient_name?: string;
  owner_id?: string;
  owner_name?: string;
  owner_phone?: string;
  species?: string;
  reminder_type: ReminderType;
  title: string;
  due_date: string;
  status: ReminderStatus;
  notes?: string | null;
  last_notified_at?: string | null;
  created_at: string;
}

/* ── Staff Requests Portal ── */
export type StaffRequestType = 'leave' | 'transfer' | 'restock' | 'return' | 'general';
export type StaffRequestStatus = 'pending' | 'approved' | 'rejected';

export interface StaffRequest {
  id: string;
  user_id: string;
  user_name: string;
  user_role: UserRole;
  location_id?: string | null;
  location_name?: string | null;
  type: StaffRequestType;
  title: string;
  details: {
    // Leave
    leave_type?: 'annual' | 'sick' | 'casual' | 'exam' | 'maternity';
    start_date?: string;
    end_date?: string;
    // Transfer
    target_location_id?: string;
    target_location_name?: string;
    // Restock & Return
    product_id?: string;
    product_name?: string;
    batch_number?: string;
    quantity?: number;
    urgency?: 'low' | 'normal' | 'urgent';
    return_condition?: 'excess' | 'damaged' | 'near_expiry';
    items?: { item_name: string; quantity: number }[];
    // General / Reason
    reason: string;
    notes?: string;
  };
  status: StaffRequestStatus;
  reviewed_by?: string | null;
  reviewer_name?: string | null;
  reviewed_at?: string | null;
  review_notes?: string | null;
  created_at: string;
}

/* ── Company & Clinic Announcements ── */
export type AnnouncementScope = 'all' | 'clinic';
export type AnnouncementPriority = 'normal' | 'urgent';

export interface Announcement {
  id: string;
  title: string;
  message: string;
  scope: AnnouncementScope;
  location_id?: string | null;
  location_name?: string | null;
  author_id: string;
  author_name: string;
  author_role: UserRole;
  priority: AnnouncementPriority;
  created_at: string;
}

/* ── Controlled Substance & Pharmacy POS ── */
export interface NarcoticLog {
  id: string;
  item_id: string;
  product_name: string;
  patient_id?: string | null;
  patient_name?: string | null;
  quantity: number;
  unit?: string;
  authorized_by: string;
  authorizer_name: string;
  witness_name?: string | null;
  notes?: string | null;
  location_id?: string | null;
  created_at: string;
}

export interface DispensePrescriptionInput {
  patient_id?: string | null;
  patient_name?: string;
  items: Array<{
    product_id: string;
    product_name: string;
    quantity: number;
    unit_price: number;
    is_controlled?: boolean;
  }>;
  payment_method: 'cash' | 'pos_card' | 'bank_transfer';
  pin?: string;
  location_id?: string | null;
  user_id: string;
  authorizer_name: string;
}


