/**
 * @file types.ts
 * @description Core TypeScript type definitions for AlbionOS.
 *
 * Every interface in this file maps 1-to-1 to a table (or view) in the
 * Supabase PostgreSQL database. Field names use `snake_case` to match the
 * database column names exactly, which lets Supabase's auto-generated
 * types and RPC calls work without manual mapping.
 *
 * **Architecture role:**
 * - Shared across client components, server components, API routes,
 *   and utility functions so there is a single source of truth for
 *   every domain entity.
 * - Union types (e.g. `InvoiceStatus`) mirror PostgreSQL `CHECK`
 *   constraints and enums, keeping front-end validation in sync with
 *   the database.
 *
 * **Key exports:**
 * - Domain models: `User`, `Location`, `Product`, `InventoryItem`,
 *   `Customer`, `Invoice`, `InvoiceItem`, `Payment`, `ChatMessage`
 * - Aggregate DTO: `DashboardStats`
 * - Union / enum types: `UserRole`, `LocationType`, `InventoryStatus`,
 *   `InvoiceStatus`, `PaymentMethod`, `PaymentStatus`
 */

/* ============================================================
   Roles
   ============================================================ */

/**
 * The five application-level roles.
 *
 * Stored in the `users.role` column as a text value.
 *
 * | Value               | Description                                       |
 * |---------------------|---------------------------------------------------|
 * | `super_admin`       | Full platform access, can manage users & settings |
 * | `sales_rep`         | Field rep — creates orders, manages customers     |
 * | `finance_manager`   | Approves payments, generates financial reports    |
 * | `inventory_manager` | Manages product catalog and warehouse stock       |
 * | `ceo`               | Chief Executive Officer — read-only executive     |
 */
export type UserRole =
  | 'super_admin'
  | 'sales_rep'
  | 'finance_manager'
  | 'inventory_manager'
  | 'ceo';

/* ============================================================
   User  →  Supabase table: `users`
   ============================================================ */

/**
 * A registered user of the AlbionOS platform.
 *
 * Maps to the `users` table in Supabase. The `id` is a UUID generated by
 * Supabase Auth; the remaining profile fields are stored in a public
 * `users` table joined on `id`.
 */
export interface User {
  /** UUID primary key — matches the Supabase Auth `auth.users.id`. */
  id: string;

  /** Corporate email, unique, used as the login credential. */
  email: string;

  /** Full display name (e.g. "Dr. Emeka Moneke"). */
  full_name: string;

  /** The user's assigned role. Determines navigation and data access. */
  role: UserRole;

  /** FK → `locations.id`. Nullable for super admins who see all locations. */
  location_id: string | null;

  /** URL of the user's profile picture stored in Supabase Storage. */
  avatar_url: string | null;

  /** Phone number in E.164-ish format (e.g. "+234 803 000 0001"). */
  phone: string | null;

  /** ISO 8601 timestamp of when the user account was created. */
  created_at: string;

  /** Indicates if the user account is active or soft-deleted/suspended. */
  is_active: boolean;
}

/* ============================================================
   Location  →  Supabase table: `locations`
   ============================================================ */

/**
 * Classification of a physical Albion Pharmaceuticals location.
 *
 * | Value       | Meaning                                         |
 * |-------------|-------------------------------------------------|
 * | `warehouse` | Storage/distribution centre (e.g. HQ Warehouse) |
 * | `territory` | Sales territory covering a geographic region     |
 * | `clinic`    | A clinic or pharmacy that purchases products     |
 */
export type LocationType = 'warehouse' | 'territory' | 'clinic';

/**
 * A physical or logical location within the Albion distribution network.
 *
 * Maps to the `locations` table. Every product batch, user, and customer
 * is associated with exactly one location.
 */
export interface Location {
  /** UUID primary key. */
  id: string;

  /** Human-readable name (e.g. "HQ Warehouse", "Lagos Territory"). */
  name: string;

  /** Categorisation of the location. */
  type: LocationType;

  /** Geographic region (e.g. "South-East", "South-West"). */
  region: string;

  /** Nigerian state the location resides in (e.g. "Anambra", "Lagos"). */
  state: string;

  /** Full street address for warehouses/clinics; general area for territories. */
  address: string;
}

/* ============================================================
   Product  →  Supabase table: `products`
   ============================================================ */

/**
 * A pharmaceutical product in the Albion catalog.
 *
 * Maps to the `products` table. Each product has a unique SKU and a
 * NAFDAC (National Agency for Food and Drug Administration and Control)
 * registration number required by Nigerian regulation.
 */
export interface Product {
  /** UUID primary key. */
  id: string;

  /** Commercial product name (e.g. "Albion Paracetamol 500mg"). */
  name: string;

  /** Stock Keeping Unit — unique alphanumeric code for internal tracking. */
  sku: string;

  /** NAFDAC registration number — required for legal sale in Nigeria. */
  nafdac_number: string;

  /** Price per sellable unit in Nigerian Naira (₦). */
  unit_price: number;

  /** Product category (e.g. "Analgesic", "Antibiotic", "Vitamin"). */
  category: string;

  /** Optional longer description shown on the product detail page. */
  description: string | null;

  /** URL of the product photo stored in Supabase Storage. */
  image_url: string | null;

  /** ISO 8601 timestamp of when the product was added to the catalog. */
  created_at: string;

  /** Indicates if the product is active or soft-deleted/discontinued. */
  is_active: boolean;
}

/* ============================================================
   Inventory  →  Supabase table: `inventory`
   ============================================================ */

/**
 * Stock status of an inventory batch.
 *
 * Computed from `quantity` and `expiry_date` fields:
 *
 * | Value          | Condition                                     |
 * |----------------|-----------------------------------------------|
 * | `in_stock`     | quantity > low-stock threshold & not expired   |
 * | `low_stock`    | quantity ≤ threshold & not zero                |
 * | `out_of_stock` | quantity === 0                                 |
 * | `expired`      | expiry_date is in the past                    |
 */
export type InventoryStatus =
  | 'in_stock'
  | 'low_stock'
  | 'out_of_stock'
  | 'expired';

/**
 * A single batch of a product held at a specific location.
 *
 * Maps to the `inventory` table. The compound key of
 * `(product_id, location_id, batch_number)` is unique.
 */
export interface InventoryItem {
  /** UUID primary key. */
  id: string;

  /** FK → `products.id`. The product this batch contains. */
  product_id: string;

  /** FK → `locations.id`. The warehouse/territory holding this batch. */
  location_id: string;

  /** Number of sellable units currently in stock. */
  quantity: number;

  /** Manufacturer's batch/lot number for traceability. */
  batch_number: string;

  /** ISO 8601 date after which this batch must not be sold. */
  expiry_date: string;

  /** Current stock status. May be updated by a scheduled job or trigger. */
  status: InventoryStatus;
}

/* ============================================================
   Customer  →  Supabase table: `customers`
   ============================================================ */

/**
 * A pharmacy, hospital, or distributor that purchases from Albion.
 *
 * Maps to the `customers` table. Each customer is assigned to one
 * location (territory) and managed by the sales rep in that territory.
 */
export interface Customer {
  /** UUID primary key. */
  id: string;

  /** Contact person's full name. */
  name: string;

  /** Registered business/pharmacy name. */
  business_name: string;

  /** Primary phone number. */
  phone: string;

  /** Optional email address. */
  email: string | null;

  /** Physical address of the business. */
  address: string;

  /** Nigerian state the customer operates in. */
  state: string;

  /** Maximum credit (₦) the customer is allowed before payment is required. */
  credit_limit: number;

  /** Total unpaid amount (₦) across all invoices. Updated by payment events. */
  outstanding_balance: number;

  /** FK → `locations.id`. The territory this customer belongs to. */
  location_id: string;

  /** Indicates if the customer is active or soft-deleted. */
  is_active: boolean;
}

/* ============================================================
   Invoice  →  Supabase tables: `invoices` + `invoice_items`
   ============================================================ */

/**
 * Lifecycle status of an invoice.
 *
 * | Value     | Meaning                                            |
 * |-----------|----------------------------------------------------|
 * | `draft`   | Created but not yet sent to the customer            |
 * | `sent`    | Delivered to the customer, awaiting payment         |
 * | `paid`    | Fully paid — outstanding amount is zero             |
 * | `partial` | Partially paid — some balance remains               |
 * | `overdue` | Past the `due_date` with an outstanding balance     |
 */
export type InvoiceStatus =
  | 'draft'
  | 'sent'
  | 'paid'
  | 'partial'
  | 'overdue';

/**
 * A single line item within an invoice.
 *
 * Maps to the `invoice_items` table. An invoice has one or more items.
 */
export interface InvoiceItem {
  /** UUID primary key. */
  id: string;

  /** FK → `products.id`. */
  product_id: string;

  /** Denormalised product name for display (avoids extra join on read). */
  product_name: string;

  /** Number of units sold in this line item. */
  quantity: number;

  /** Price per unit (₦) at the time of invoicing (may differ from catalog price). */
  unit_price: number;

  /** Line total (₦): `quantity × unit_price`. */
  total: number;
}

/**
 * A sales invoice issued to a customer.
 *
 * Maps to the `invoices` table. Contains header-level data; line items
 * are stored separately in `InvoiceItem[]`.
 */
export interface Invoice {
  /** UUID primary key. */
  id: string;

  /** Human-readable invoice number (e.g. "INV-2026-001"). Auto-generated. */
  invoice_number: string;

  /** FK → `customers.id`. The customer being billed. */
  customer_id: string;

  /** FK → `users.id`. The sales rep who created the invoice. */
  sales_rep_id: string;

  /** FK → `locations.id`. The territory/warehouse the order ships from. */
  location_id: string;

  /** Array of line items (embedded from `invoice_items` table). */
  items: InvoiceItem[];

  /** Sum of all line item totals before tax (₦). */
  subtotal: number;

  /** VAT amount (₦). Currently 7.5% in Nigeria. */
  vat: number;

  /** Grand total (₦): `subtotal + vat`. */
  total: number;

  /** Current lifecycle status. */
  status: InvoiceStatus;

  /** ISO 8601 timestamp of invoice creation. */
  created_at: string;

  /** ISO 8601 date by which payment is expected. */
  due_date: string;
}

/* ============================================================
   Payment  →  Supabase table: `payments`
   ============================================================ */

/**
 * How the customer paid.
 *
 * | Value           | Description                              |
 * |-----------------|------------------------------------------|
 * | `cash`          | Physical cash payment to the sales rep   |
 * | `bank_transfer` | Electronic bank transfer (with proof)    |
 */
export type PaymentMethod = 'cash' | 'bank_transfer';

/**
 * Approval status of a payment record.
 *
 * | Value      | Description                                          |
 * |------------|------------------------------------------------------|
 * | `pending`  | Recorded by the sales rep, awaiting finance approval  |
 * | `approved` | Verified and approved by a finance manager             |
 * | `rejected` | Rejected — proof insufficient or amount mismatch      |
 */
export type PaymentStatus = 'pending' | 'approved' | 'rejected';

/**
 * A payment received against an invoice.
 *
 * Maps to the `payments` table. A single invoice can have multiple
 * partial payments until the outstanding balance reaches zero.
 */
export interface Payment {
  /** UUID primary key. */
  id: string;

  /** FK → `invoices.id`. The invoice this payment applies to. */
  invoice_id: string;

  /** FK → `customers.id`. The customer who made the payment. */
  customer_id: string;

  /** Amount paid (₦). May be less than the invoice total (partial payment). */
  amount: number;

  /** How the payment was made. */
  method: PaymentMethod;

  /** URL of uploaded payment proof (e.g. bank transfer receipt image). */
  proof_url: string | null;

  /** Current approval status. */
  status: PaymentStatus;

  /** FK → `users.id`. The sales rep who recorded this payment. */
  recorded_by: string;

  /** FK → `users.id`. The finance manager who approved/rejected. Null until actioned. */
  approved_by: string | null;

  /** Optional free-text notes (e.g. rejection reason). */
  notes: string | null;

  /** ISO 8601 timestamp of when the payment was recorded. */
  created_at: string;
}

/* ============================================================
   Chat  →  Supabase table: `chat_messages`
   ============================================================ */

/**
 * A single message in the internal chat system.
 *
 * Maps to the `chat_messages` table. Messages are direct (1-to-1)
 * between a sender and a receiver. Group chat is not yet supported.
 */
export interface ChatMessage {
  /** UUID primary key. */
  id: string;

  /** FK → `users.id`. The user who sent the message. */
  sender_id: string;

  /** FK → `users.id`. The intended recipient. */
  receiver_id: string;

  /** The text body of the message. */
  content: string;

  /** URL of an attached file (image, PDF, etc.) in Supabase Storage. */
  attachment_url: string | null;

  /** MIME-type hint for the attachment (e.g. "image/png", "application/pdf"). */
  attachment_type: string | null;

  /** Whether the receiver has opened/read this message. */
  is_read: boolean;

  /** ISO 8601 timestamp of when the message was sent. */
  created_at: string;
}

/* ============================================================
   Dashboard  →  Aggregated view / RPC result
   ============================================================ */

/**
 * Aggregated statistics displayed on the main Dashboard page.
 *
 * Unlike the other interfaces this does **not** map to a single table.
 * The values are computed by a Supabase RPC function (or client-side
 * aggregation during the mock phase) that joins across invoices,
 * payments, inventory, and users.
 */
export interface DashboardStats {
  /** Total revenue (₦) from all paid/partial invoices. */
  total_revenue: number;

  /** Total outstanding receivables (₦) across all unpaid invoices. */
  total_receivables: number;

  /** Number of sales reps currently active on the platform. */
  active_reps: number;

  /** Total value (₦) of all products currently in stock. */
  inventory_value: number;

  /** Count of payments in `pending` status awaiting finance approval. */
  pending_payments: number;

  /** Count of inventory batches expiring within the next 90 days. */
  expiring_soon: number;
}

/* ============================================================
   Staff & Salary Management
   ============================================================ */

export type LeaveType = 'annual' | 'sick' | 'personal' | 'maternity' | 'paternity' | 'study';

export type LeaveStatus = 'pending' | 'approved' | 'rejected' | 'cancelled';

export type PayrollRunStatus = 'draft' | 'processing' | 'completed' | 'cancelled';

export type AttendanceStatus = 'present' | 'absent' | 'late' | 'half_day' | 'on_leave';

export type TargetType = 'monthly' | 'quarterly' | 'annual';

export type TargetStatus = 'active' | 'achieved' | 'missed' | 'cancelled';

export type DocumentType = 'contract' | 'id_card' | 'certification' | 'degree' | 'nafdac_license' | 'other';

export interface SalaryGrade {
  id: string;
  grade: string;
  min_salary: number;
  max_salary: number;
  housing_allowance_pct: number;
  transport_allowance_pct: number;
  medical_allowance_pct: number;
  created_at: string;
}

export interface Salary {
  id: string;
  user_id: string;
  salary_grade_id: string;
  basic_salary: number;
  housing_allowance: number;
  transport_allowance: number;
  medical_allowance: number;
  total_gross: number;
  tax_rate: number;
  pension_rate: number;
  nhis_rate: number;
  total_deductions: number;
  net_pay: number;
  effective_date: string;
  is_active: boolean;
  created_at: string;
  updated_at: string;
}

export interface PayrollRun {
  id: string;
  period_start: string;
  period_end: string;
  payment_date: string;
  status: PayrollRunStatus;
  total_gross: number;
  total_deductions: number;
  total_net: number;
  employee_count: number;
  processed_by: string;
  created_at: string;
  updated_at: string;
}

export interface Payslip {
  id: string;
  payroll_run_id: string;
  user_id: string;
  basic_salary: number;
  housing_allowance: number;
  transport_allowance: number;
  medical_allowance: number;
  gross_pay: number;
  paye_tax: number;
  pension_deduction: number;
  nhis_deduction: number;
  total_deductions: number;
  net_pay: number;
  created_at: string;
}

export interface LeaveRequest {
  id: string;
  user_id: string;
  leave_type: LeaveType;
  start_date: string;
  end_date: string;
  duration_days: number;
  reason: string;
  status: LeaveStatus;
  approved_by: string | null;
  reviewed_at: string | null;
  reviewer_notes: string | null;
  created_at: string;
  updated_at: string;
}

export interface LeaveBalance {
  id: string;
  user_id: string;
  leave_type: LeaveType;
  total_days: number;
  used_days: number;
  remaining_days: number;
  year: number;
  created_at: string;
  updated_at: string;
}

export interface AttendanceLog {
  id: string;
  user_id: string;
  date: string;
  clock_in: string | null;
  clock_out: string | null;
  status: AttendanceStatus;
  hours_worked: number | null;
  notes: string | null;
  created_at: string;
  updated_at: string;
}

export interface EmployeeDocument {
  id: string;
  user_id: string;
  document_type: DocumentType;
  document_name: string;
  file_url: string;
  file_size: number | null;
  expiry_date: string | null;
  is_verified: boolean;
  verified_by: string | null;
  notes: string | null;
  created_at: string;
  updated_at: string;
}

export interface PerformanceTarget {
  id: string;
  user_id: string;
  target_type: TargetType;
  period_start: string;
  period_end: string;
  sales_target: number;
  actual_sales: number;
  collection_target: number;
  actual_collection: number;
  new_customers_target: number;
  new_customers_actual: number;
  status: TargetStatus;
  notes: string | null;
  created_at: string;
  updated_at: string;
}

export interface PerformanceReview {
  id: string;
  user_id: string;
  reviewer_id: string;
  review_period: string;
  sales_achievement: number | null;
  collection_rate: number | null;
  customer_satisfaction: number | null;
  overall_rating: number | null;
  comments: string | null;
  created_at: string;
  updated_at: string;
}

/* ============================================================
   Pet Clinic Management
   ============================================================ */

export type Species = 'Dog' | 'Cat' | 'Bird' | 'Rabbit' | 'Fish' | 'Reptile' | 'Horse' | 'Goat' | 'Sheep' | 'Cattle' | 'Poultry' | 'Other';

export type PetGender = 'Male' | 'Female';

export type AppointmentStatus = 'scheduled' | 'checked_in' | 'in_progress' | 'completed' | 'cancelled' | 'no_show';

export type TreatmentStatus = 'ongoing' | 'completed' | 'cancelled';

export type QueueStatus = 'waiting' | 'in_progress' | 'completed' | 'cancelled' | 'no_show';

export type QueuePriority = 'normal' | 'urgent' | 'emergency';

export interface Patient {
  id: string;
  owner_id: string;
  name: string;
  species: Species;
  breed: string | null;
  gender: PetGender;
  date_of_birth: string | null;
  age_years: number | null;
  age_months: number | null;
  weight_kg: number | null;
  color: string | null;
  microchip_id: string | null;
  spayed_neutered: boolean;
  allergies: string | null;
  medical_notes: string | null;
  is_active: boolean;
  created_at: string;
  updated_at: string;
}

export interface Appointment {
  id: string;
  patient_id: string;
  owner_id: string;
  vet_id: string | null;
  location_id: string | null;
  procedure_type: string | null;
  date: string;
  time: string;
  duration_minutes: number;
  reason: string | null;
  status: AppointmentStatus;
  notes: string | null;
  created_at: string;
  updated_at: string;
}

export interface Treatment {
  id: string;
  patient_id: string;
  vet_id: string;
  date: string;
  chief_complaint: string | null;
  diagnosis: string | null;
  assessment: string | null;
  plan: string | null;
  status: TreatmentStatus;
  follow_up_date: string | null;
  total_cost: number;
  created_at: string;
  updated_at: string;
}

export interface TreatmentMedication {
  id: string;
  treatment_id: string;
  inventory_item_id: string | null;
  drug_name: string;
  dosage: string;
  route: string;
  frequency: string;
  duration: string;
  quantity: number;
  unit_price: number;
  total: number;
  created_at: string;
}

export interface PatientQueue {
  id: string;
  patient_id: string;
  owner_id: string;
  location_id: string | null;
  department: string;
  priority: QueuePriority;
  status: QueueStatus;
  reason: string | null;
  assigned_vet_id: string | null;
  called_at: string | null;
  completed_at: string | null;
  created_at: string;
  updated_at: string;
}

export interface VetService {
  id: string;
  name: string;
  description: string | null;
  category: string;
  species: string;
  price: number;
  is_active: boolean;
  created_at: string;
  updated_at: string;
}
