-- ============================================================================
-- AlbionOS — Create Auth Users for Demo Accounts
-- ============================================================================
-- Run this in your Supabase Dashboard → SQL Editor
--
-- This creates 4 auth users with the password 'AlbionTest123!' and then
-- updates their profile rows in the `profiles` table to link them.
--
-- IMPORTANT: Run this AFTER schema.sql and seed.sql have been executed.
-- ============================================================================

-- 1. Create auth users with email/password credentials
-- The `id` values here will be generated by Supabase Auth automatically.
-- We'll then update profiles to match.

-- Admin user
INSERT INTO auth.users (
  instance_id, id, aud, role, email, encrypted_password,
  email_confirmed_at, created_at, updated_at,
  confirmation_token, recovery_token, email_change_token_new,
  raw_app_meta_data, raw_user_meta_data
) VALUES (
  '00000000-0000-0000-0000-000000000000',
  gen_random_uuid(),
  'authenticated', 'authenticated',
  'admin@albionpharma.com',
  crypt('AlbionTest123!', gen_salt('bf')),
  NOW(), NOW(), NOW(),
  '', '', '',
  '{"provider":"email","providers":["email"]}',
  '{"full_name":"Dr. Emeka Moneke"}'
);

-- Sales Rep
INSERT INTO auth.users (
  instance_id, id, aud, role, email, encrypted_password,
  email_confirmed_at, created_at, updated_at,
  confirmation_token, recovery_token, email_change_token_new,
  raw_app_meta_data, raw_user_meta_data
) VALUES (
  '00000000-0000-0000-0000-000000000000',
  gen_random_uuid(),
  'authenticated', 'authenticated',
  'chidi@albionpharma.com',
  crypt('AlbionTest123!', gen_salt('bf')),
  NOW(), NOW(), NOW(),
  '', '', '',
  '{"provider":"email","providers":["email"]}',
  '{"full_name":"Chidi Okafor"}'
);

-- Finance Manager
INSERT INTO auth.users (
  instance_id, id, aud, role, email, encrypted_password,
  email_confirmed_at, created_at, updated_at,
  confirmation_token, recovery_token, email_change_token_new,
  raw_app_meta_data, raw_user_meta_data
) VALUES (
  '00000000-0000-0000-0000-000000000000',
  gen_random_uuid(),
  'authenticated', 'authenticated',
  'ngozi@albionpharma.com',
  crypt('AlbionTest123!', gen_salt('bf')),
  NOW(), NOW(), NOW(),
  '', '', '',
  '{"provider":"email","providers":["email"]}',
  '{"full_name":"Ngozi Eze"}'
);

-- CEO
INSERT INTO auth.users (
  instance_id, id, aud, role, email, encrypted_password,
  email_confirmed_at, created_at, updated_at,
  confirmation_token, recovery_token, email_change_token_new,
  raw_app_meta_data, raw_user_meta_data
) VALUES (
  '00000000-0000-0000-0000-000000000000',
  gen_random_uuid(),
  'authenticated', 'authenticated',
  'ceo@albionpharma.com',
  crypt('AlbionTest123!', gen_salt('bf')),
  NOW(), NOW(), NOW(),
  '', '', '',
  '{"provider":"email","providers":["email"]}',
  '{"full_name":"CEO Albion"}'
);

-- Inventory Manager
INSERT INTO auth.users (
  instance_id, id, aud, role, email, encrypted_password,
  email_confirmed_at, created_at, updated_at,
  confirmation_token, recovery_token, email_change_token_new,
  raw_app_meta_data, raw_user_meta_data
) VALUES (
  '00000000-0000-0000-0000-000000000000',
  gen_random_uuid(),
  'authenticated', 'authenticated',
  'tunde@albionpharma.com',
  crypt('AlbionTest123!', gen_salt('bf')),
  NOW(), NOW(), NOW(),
  '', '', '',
  '{"provider":"email","providers":["email"]}',
  '{"full_name":"Tunde Adeyemi"}'
);

-- 2. Now update the `profiles` table to use the auth.users UUIDs
-- First, delete the old seed profiles (they have placeholder IDs)
DELETE FROM profiles;

-- 3. Re-insert profiles with the real auth.users UUIDs
-- These will be matched by email to the auth users we just created

INSERT INTO profiles (id, email, full_name, role, location_id, phone)
SELECT
  au.id,
  au.email,
  au.raw_user_meta_data->>'full_name',
  CASE au.email
    WHEN 'admin@albionpharma.com' THEN 'super_admin'
    WHEN 'chidi@albionpharma.com' THEN 'sales_rep'
    WHEN 'ngozi@albionpharma.com' THEN 'finance_manager'
    WHEN 'tunde@albionpharma.com' THEN 'inventory_manager'
    WHEN 'ceo@albionpharma.com' THEN 'ceo'
  END,
  CASE au.email
    WHEN 'admin@albionpharma.com' THEN (SELECT id FROM locations WHERE name LIKE '%HQ%' OR name LIKE '%Onitsha%' LIMIT 1)
    WHEN 'chidi@albionpharma.com' THEN (SELECT id FROM locations WHERE name LIKE '%Lagos%' LIMIT 1)
    WHEN 'ngozi@albionpharma.com' THEN (SELECT id FROM locations WHERE name LIKE '%HQ%' OR name LIKE '%Onitsha%' LIMIT 1)
    WHEN 'tunde@albionpharma.com' THEN (SELECT id FROM locations WHERE name LIKE '%HQ%' OR name LIKE '%Onitsha%' LIMIT 1)
    WHEN 'ceo@albionpharma.com' THEN (SELECT id FROM locations WHERE name LIKE '%HQ%' OR name LIKE '%Onitsha%' LIMIT 1)
  END,
  CASE au.email
    WHEN 'admin@albionpharma.com' THEN '+234 803 000 0001'
    WHEN 'chidi@albionpharma.com' THEN '+234 803 000 0002'
    WHEN 'ngozi@albionpharma.com' THEN '+234 803 000 0003'
    WHEN 'tunde@albionpharma.com' THEN '+234 803 000 0004'
    WHEN 'ceo@albionpharma.com' THEN '+234 803 000 0005'
  END
FROM auth.users au
WHERE au.email IN (
  'admin@albionpharma.com',
  'chidi@albionpharma.com',
  'ngozi@albionpharma.com',
  'tunde@albionpharma.com',
  'ceo@albionpharma.com'
);

-- 4. Update any invoice/payment foreign keys that reference old user IDs
-- to point to the new auth user UUIDs
UPDATE invoices SET sales_rep_id = (
  SELECT id FROM profiles WHERE email = 'chidi@albionpharma.com' LIMIT 1
) WHERE sales_rep_id IS NOT NULL;

UPDATE payments SET recorded_by = (
  SELECT id FROM profiles WHERE email = 'chidi@albionpharma.com' LIMIT 1
) WHERE recorded_by IS NOT NULL;

-- 5. Create identities for each auth user (required for email login)
INSERT INTO auth.identities (
  id, user_id, provider_id, identity_data, provider, last_sign_in_at, created_at, updated_at
)
SELECT
  au.id,
  au.id,
  au.email,
  jsonb_build_object('sub', au.id::text, 'email', au.email),
  'email',
  NOW(), NOW(), NOW()
FROM auth.users au
WHERE au.email IN (
  'admin@albionpharma.com',
  'chidi@albionpharma.com',
  'ngozi@albionpharma.com',
  'tunde@albionpharma.com',
  'ceo@albionpharma.com'
);

-- Verify: Check that everything is linked
SELECT
  p.id,
  p.email,
  p.full_name,
  p.role,
  l.name as location_name,
  (SELECT COUNT(*) FROM auth.users au WHERE au.id = p.id) as has_auth_user
FROM profiles p
LEFT JOIN locations l ON l.id = p.location_id
ORDER BY p.email;
